
#Makefile for lab3
#Currently running lab3 on lab3_2.c, linked list implementation
#Grace Humer, CMPT201 - Summer 2026

run: lab3		#Runs lab3 executable
	./lab3

lab3: lab3.c			#compile executable
	clang -fsanitize=address lab3.c -o lab3
