
#Makefile for lab3
#Currently running lab3 on lab3_2.c, linked list implementation
#Grace Humer, CMPT201 - Summer 2026

run: lab3		#Runs lab3 executable
	./lab3

lab3: lab3_2.c			#compile executable: TODO RENAME TO lab3.c before submission
	clang lab3_2.c -o lab3
